FROM tomcat
RUN wget --user=admin --password=lotfi -P /usr/local/tomcat/webapps http://10.10.20.31:8081/repository/hello_livrable/dernier_rondoudou_fiable.war
#COPY rondoudou.war /usr/local/tomcat/webapps
